<#
.SYNOPSIS
    hx installer for Windows — downloads a prebuilt binary, verifies it, puts it on your PATH.

.DESCRIPTION
    Downloads the release archive for this machine's architecture, verifies its SHA-256
    against the released SHA256SUMS, and installs hx.exe and hxd.exe.

.EXAMPLE
    iwr -useb https://raw.githubusercontent.com/phantomic12/hx-harness/main/install.ps1 | iex

.EXAMPLE
    # Pin a version and choose the destination
    .\install.ps1 -Version 0.0.1 -InstallDir C:\tools\hx
#>
[CmdletBinding()]
param(
    [string] $Version    = $env:HX_VERSION,
    [string] $InstallDir = $(if ($env:HX_INSTALL_DIR) { $env:HX_INSTALL_DIR } else { Join-Path $env:LOCALAPPDATA 'hx\bin' })
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Repo = 'phantomic12/hx-harness'

# Windows PowerShell 5.1 still defaults to TLS 1.0 for WebRequest unless told otherwise,
# which GitHub refuses. Harmless no-op on PowerShell 7+.
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}

function Say  { param([string]$m) Write-Host "  $m" }
function Head { param([string]$m) Write-Host "`n$m" -ForegroundColor White }
function Die  { param([string]$m) Write-Host "`nerror: $m" -ForegroundColor Red; exit 1 }

# ---------------------------------------------------------------------------
# Which build does this machine need?
# ---------------------------------------------------------------------------
# PROCESSOR_ARCHITEW6432 is set when a 32-bit shell runs on 64-bit Windows — it holds
# the real architecture. Prefer it so a 32-bit PowerShell still gets the x64 build.
$arch = if ($env:PROCESSOR_ARCHITEW6432) { $env:PROCESSOR_ARCHITEW6432 } else { $env:PROCESSOR_ARCHITECTURE }

switch ($arch) {
    'AMD64' { $target = 'x86_64-pc-windows-msvc' }
    'ARM64' {
        Die @"
Windows on ARM (aarch64) builds are not published yet.

    Options:
      - Use the x64 build under emulation (usually fine):
            `$env:HX_VERSION stays the same; download x86_64-pc-windows-msvc manually
      - Build from source:  cargo build --release
"@
    }
    default { Die "unsupported architecture '$arch'. Expected AMD64 or ARM64." }
}

Head "hx installer"
Say "platform : windows/$arch -> $target"

# ---------------------------------------------------------------------------
# Resolve the version
# ---------------------------------------------------------------------------
if (-not $Version) {
    Say "version  : resolving latest release..."
    try {
        $rel = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest" -UseBasicParsing
    } catch {
        Die "could not query GitHub for the latest release. Set HX_VERSION to install a specific build.`n         $($_.Exception.Message)"
    }
    $Version = $rel.tag_name -replace '^v', ''
    if (-not $Version) { Die "latest release has no tag name; set HX_VERSION explicitly." }
}
$Version = $Version -replace '^v', ''
Say "version  : $Version"

$archive = "hx-$Version-$target.zip"
$base    = "https://github.com/$Repo/releases/download/v$Version"
$url     = "$base/$archive"

# ---------------------------------------------------------------------------
# Download into a scratch directory we always clean up
# ---------------------------------------------------------------------------
$tmp = Join-Path ([IO.Path]::GetTempPath()) ("hx-install-" + [Guid]::NewGuid().ToString('N').Substring(0, 8))
New-Item -ItemType Directory -Path $tmp -Force | Out-Null

try {
    Head "Downloading"
    Say $url
    try {
        Invoke-WebRequest -Uri $url -OutFile (Join-Path $tmp $archive) -UseBasicParsing
    } catch {
        Die "download failed. Does release v$Version exist, and is there a $target build?`n         $url`n         $($_.Exception.Message)"
    }

    # -----------------------------------------------------------------------
    # Verify. Downloading over TLS already proves origin; this proves the file
    # is byte-for-byte what the release published (catches truncation + CDN issues).
    # -----------------------------------------------------------------------
    Head "Verifying checksum"
    $sumsPath = Join-Path $tmp 'SHA256SUMS'
    try {
        Invoke-WebRequest -Uri "$base/SHA256SUMS" -OutFile $sumsPath -UseBasicParsing
    } catch {
        Die "could not download SHA256SUMS; refusing to install an unverified binary."
    }

    # Release checksums are generated by `sha256sum`, i.e. "<hash>  <name>" (possibly
    # with a ./* prefix). Match on the bare filename.
    $expected = $null
    foreach ($line in Get-Content $sumsPath) {
        $parts = $line -split '\s+', 2
        if ($parts.Count -eq 2) {
            $name = $parts[1].Trim() -replace '^\./', ''
            if ($name -eq $archive) { $expected = $parts[0].Trim().ToLower(); break }
        }
    }
    if (-not $expected) { Die "no checksum for '$archive' in SHA256SUMS — refusing to install." }

    $actual = (Get-FileHash -Path (Join-Path $tmp $archive) -Algorithm SHA256).Hash.ToLower()
    if ($actual -ne $expected) {
        Die "CHECKSUM MISMATCH for $archive`n         expected $expected`n         actual   $actual`n         Refusing to install."
    }
    Say "ok  $($actual.Substring(0,16))..."

    # -----------------------------------------------------------------------
    # Extract and install
    # -----------------------------------------------------------------------
    Head "Installing to $InstallDir"
    $stage = Join-Path $tmp 'stage'
    Expand-Archive -Path (Join-Path $tmp $archive) -DestinationPath $stage -Force

    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    $installed = @()
    foreach ($exe in @('hx.exe', 'hxd.exe')) {
        $found = Get-ChildItem -Path $stage -Filter $exe -Recurse -File | Select-Object -First 1
        if (-not $found) { Die "'$exe' not found inside $archive — the release archive is malformed." }
        Copy-Item $found.FullName (Join-Path $InstallDir $exe) -Force
        $installed += $exe
    }
    Say ("installed: " + ($installed -join ', '))
}
finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}

# ---------------------------------------------------------------------------
# Get it on the PATH (user scope — no admin rights needed)
# ---------------------------------------------------------------------------
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
if (($userPath -split ';') -notcontains $InstallDir) {
    $newPath = if ([string]::IsNullOrEmpty($userPath)) { $InstallDir } else { "$userPath;$InstallDir" }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Say "added $InstallDir to your user PATH"
    Say "(open a new terminal for that to take effect)"
} else {
    Say "$InstallDir is already on your PATH"
}

Head "Version check"
try { & (Join-Path $InstallDir 'hxd.exe') --version } catch { Say "(could not run hxd --version: $($_.Exception.Message))" }

Head "Done"
Say "Installed hx and hxd $Version to $InstallDir"
Say ""
Say "Next steps:"
Say "  hxd --config hx.yaml          # start the daemon (needs a config)"
Say "  hx --help                     # CLI"
Say ""
Say "Docs: https://github.com/$Repo/blob/main/DEPLOY.md"
